### ISSUE TITLE
Merged-mining has come to a halt except for ViaBTC and BTC.COM

### ISSUE THREAD

**Issue by cassiniNMC** [namecoin/namecoin-core#227] opened 2018-06-18 11:16 UTC
During the last 24 hours only ViaBTC and BTC.COM have been able to include blocks in the active Namecoin blockchain. The latest block from a mining pool other than ViaBTC or BTC.COM is block #403465 found by Bixin at 2018-06-17 10:49:03 UTC, i.e. 24 hours ago. As a result the visible block-finding rate has dropped to 2.1 blocks/hour.

It seems it is not related to BTC vs. BCH mining. ViaBTC, for instance, is using both blockchains as the parent blockchains for merged-mining as usual.

I'm wondering if this issue is anything to do with the recent commit https://github.com/bitcoin/bitcoin/commit/e802c2294718f1e1128f2736842595c3b84a2882 (remove miner's _blockmaxsize_ option).

**Comment by JeremyRand** [comment] 2018-06-18 11:54
> During the last 24 hours only ViaBTC and BTC.COM have been able to include blocks in the active Namecoin blockchain.

@cassiniNMC What's the list of mining pools who seem to have dropped out, and what fraction of hashrate did each of them have before the dropout?

**Comment by cassiniNMC** [comment] 2018-06-18 12:09
Coincidentially I made this list for @domob1812 last night and posted it on the forum,
See https://forum.namecoin.org/viewtopic.php?f=6&t=2700
when things already looked slightly unusual but nothing to worry about. This morning I had a closer look just to find out that all the other mining pools have issues.

**Comment by JeremyRand** [comment] 2018-06-18 12:52
I've just contacted the BTC.TOP CEO via Twitter.  https://twitter.com/Namecoin/status/1008693600648081408

**Comment by JeremyRand** [comment] 2018-06-18 13:06
I've just contacted Slush via their web contact form.

**Comment by JeremyRand** [comment] 2018-06-18 13:13
Hi @wangchun, sorry to bother you, @cassiniNMC is reporting an apparent drop-off in Namecoin hashrate from F2Pool.  Any chance you could check whether there's any technical issue impacting Namecoin mining on F2Pool?  Thanks!

**Comment by JeremyRand** [comment] 2018-06-18 14:18
Stats I'm seeing for all blocks mined today (i.e. after June 18 12:01 AM UTC):

~~~
Stats from 403489 to 403523 (35 blocks):

  Total     %  Pool or Miner, Blockversion
     21  60.0  BTC.com-10104
     14  40.0  ViaBTC-10104
~~~

**Comment by cassiniNMC** [comment] 2018-06-18 14:34
I think we need to get in touch with ViaBTC and BTC.COM and ask them if they changed anything around their server setup during the last few days, e.g. updating the Bitcoin or the Namecoin client to a different version, or tinkering with the _blockmaxsize vs. blockmaxweight_ issue (see abovementioned Bitcoin commit).

**Comment by JeremyRand** [comment] 2018-06-18 14:43
Coincidentally, https://www.f2pool.com is timing out for me in both Tor Browser and Firefox (over Tor) today.

**Comment by JeremyRand** [comment] 2018-06-18 14:44
> I think we need to get in touch with ViaBTC and BTC.COM and ask them if they made any consensus-related changes during the last few days, e.g. updating the Bitcoin or the Namecoin client to a different version, or tinkering with the blockmaxsize vs. blockmaxweight issue (see abovementioned Bitcoin commit).

@cassiniNMC Yeah, seems like a worthwhile thing to investigate,

**Comment by JeremyRand** [comment] 2018-06-18 14:50
FWIW it's obvious that ViaBTC and BTC.com didn't accidentally activate a hardfork, since my old Namecoin Core client from 2016 is still accepting their blocks.  So if there's an accidental consensus fork happening at those 2 pools, it's a softfork.

**Comment by JeremyRand** [comment] 2018-06-18 15:02
I've just sent the following email to BTC.com's support address:

> Hi BTC.com,
> 
> I'm the lead application engineer at Namecoin.  One of our developers has noticed some hashrate distribution issues in the last day or two; it looks like BTC.com and ViaBTC are the only two mining pools who have mined any blocks in the longest valid Namecoin chain in the last day.  We're wondering whether you may have made any consensus-related changes to your setup during the last few days, e.g. updating the Bitcoin or the Namecoin client to a different version, or tinkering with the blockmaxsize or blockmaxweight options.
> 
> The relevant GitHub issue where we're tracking the investigation is https://github.com/namecoin/namecoin-core/issues/227 ; feel free to post there if you like.
> 
> Thanks,
> -Jeremy Rand

**Comment by JeremyRand** [comment] 2018-06-18 15:05
@cassiniNMC Do you have a Namecoin Core node that's been running continuously since before the issue began?  If so, can you paste the output of `namecoin-cli getchaintips` here?

**Comment by JeremyRand** [comment] 2018-06-18 15:14
I've just sent a similar email to ViaBTC's support email address as I did for BTC.com.

**Comment by JeremyRand** [comment] 2018-06-18 19:19
F2Pool's website is back up, I've just emailed F2Pool.

**Comment by cassiniNMC** [comment] 2018-06-18 19:42
> Do you have a Namecoin Core node that's been running continuously since before the issue began? If so, can you paste the output of namecoin-cli getchaintips here?

No, unfortunately not. I've just pinged Daniel. Maybe he can provide us with some data on this.

**Comment by JeremyRand** [comment] 2018-06-18 20:12
@redblade7 you have a Namecoin seed node, right?  Has it been running continuously for the past week or so?  If so, can you paste the output of `namecoin-cli getchaintips` here?

**Comment by JeremyRand** [comment] 2018-06-19 00:09
Namecoin Core is now displaying the following warning: "WARNING: check your network connection, 5 blocks received in the last 4 hours (24 expected)".

**Comment by redblade7** [comment] 2018-06-19 00:55
Hi, I've been getting emails for this, but wondering why, guess I missed the message from Jeremy.

**Comment by redblade7** [comment] 2018-06-19 00:58
[getchaintips.txt](https://github.com/namecoin/namecoin-core/files/2113458/getchaintips.txt)

**Comment by JeremyRand** [comment] 2018-06-19 01:13
Thanks @redblade7.  AFAICT the most recent chainfork in that log is from June 3, so I don't think we're seeing an accidental softfork here.

**Comment by wangchun** [comment] 2018-06-19 06:33
I am asking our devs to check from our side.

**Comment by domob1812** [comment] 2018-06-19 06:59
Yes, I do have a node running.  But `getchaintips` does not show anything interesting for me, either - the last fork was at block 401432, and only a single orphan block.  (In fact, the whole output only shows alternate chains of length up to one.)

So it does indeed look to neither be an accidental soft- nor hardfork, at least not with the standard client configuration.  It could of course be that the dropped-out pools have some non-standard config and are forked off because of that - and/or stopped producing valid blocks at all (not even on a valid branch) for some reason.  But then it is strange that multiple other pools seem to be having issues at the same time.

For now, I think we should hope to get some insight from those pools directly - perhaps they are seeing some useful information in their `debug.log`, or otherwise know of something going on.

**Comment by cassiniNMC** [comment] 2018-06-19 15:02
@wangchun This looks very promising. Five F2Pool blocks have been included in the active blockchain this morning (UTC). No blocks from F2Pool during the last 3 hours, though.

```
block# UTC                  #tx   mining pool
403566 2018-06-19 08:17:58   17   F2Pool
403567 2018-06-19 08:45:29    1   ViaBTC
403568 2018-06-19 09:07:49  131   BTC.COM
403569 2018-06-19 09:36:00    4   F2Pool
403570 2018-06-19 09:38:08    1   ViaBTC
403571 2018-06-19 09:56:21    2   BTC.COM
403572 2018-06-19 10:00:51    1   F2Pool
403573 2018-06-19 10:24:11    2   BTC.COM
403574 2018-06-19 10:43:46    1   F2Pool
403575 2018-06-19 11:39:49    3   F2Pool
...
403586 2018-06-19 14:48:25    1   BTC.COM
```

**Comment by cassiniNMC** [comment] 2018-06-19 15:10
@wangchun Well done, another F2Pool block has just arrived:

`403588 2018-06-19 15:03:07    2   F2Pool`

**Comment by JeremyRand** [comment] 2018-06-19 15:12
Indeed, I can confirm from my node that 6 F2Pool blocks appear in the last 36 blocks (one of which was in the last few minutes).  I'm very curious whether F2Pool did anything in particular to fix things.  The other missing pools have not yet re-appeared.

**Comment by JeremyRand** [comment] 2018-06-19 16:49
Hi @wangchun , any news on F2Pool's investigation?  It definitely looks like you've solved the issue on F2Pool's end; we'd very much like to know what your analysis revealed so that we can get the other pools fixed ASAP.

**Comment by JeremyRand** [comment] 2018-06-19 17:01
Here's another data point.  So I just looked at [the most recent BTC.TOP Bitcoin block](https://blockchainbdgpzk.onion/tx/f0aeb38af7f92fc7573ccc0c8f0c49469b570541f1e693ccd35305a277f45a30?show_adv=true).  Its coinbase does have an AuxPoW header (`fabe6d6d`), even though BTC.TOP doesn't seem to be adding any blocks to the Namecoin chain.

**Comment by JeremyRand** [comment] 2018-06-19 18:42
We might have a possible explanation for the issue.  A `getblocktemplate` bug got triggered by transactions that entered the mempool 2 days ago -- around the same time as this issue began.  https://github.com/namecoin/namecoin-core/issues/50#issuecomment-397879723

**Comment by JeremyRand** [comment] 2018-06-19 22:21
Since we have [a workaround](https://github.com/namecoin/namecoin-core/issues/50#issuecomment-398551910) now, I've just sent an email to the Alerts mailing list telling them how to get their miners working again.

**Comment by YihaoPeng** [comment] 2018-06-20 02:59
I'm BTC.COM's developer. The issue #50 causes all our namecoin nodes "denial of mining" at 17th Jun, 11:20 (UTC).

I found deleting `mempool.dat` can recovery the node. So our mining soon returned to normal.

**Comment by JeremyRand** [comment] 2018-06-20 04:40
@YihaoPeng thanks.  Indeed, this makes sense.  Since your mining is currently operational and I have your attention, would you be willing to prioritize [transaction 16ba9e81c0cb48510a2f587851e10eff4aecda4fa7019c3f9b2cf7784fa70a22](https://bchain.info/NMC/tx/16ba9e81c0cb48510a2f587851e10eff4aecda4fa7019c3f9b2cf7784fa70a22)?  I'm hoping that mining that transaction will help the other pools recover more quickly.

**Comment by JeremyRand** [comment] 2018-06-20 06:07
Looks like F2Pool has dropped out again; I don't see any F2Pool blocks in the last 36 Namecoin blocks.

**Comment by YihaoPeng** [comment] 2018-06-20 06:30
OK, I will try `prioritisetransaction`.

**Comment by domob1812** [comment] 2018-06-20 07:10
Please note that it is enough for one miner to succeed in mining `16ba9e81c0cb48510a2f587851e10eff4aecda4fa7019c3f9b2cf7784fa70a22` using `prioritisetransaction` or any other hack.  Once that is done, all others will be fixed automatically.  (But so far, it seems that both offending transactions are still unconfirmed.)

I will fix #50 now properly, which should also make this issue go away (as soon as someone updates and mines the transactions properly).

**Comment by YihaoPeng** [comment] 2018-06-20 08:37
https://namecha.in/tx/16ba9e81c0cb48510a2f587851e10eff4aecda4fa7019c3f9b2cf7784fa70a22 was confirmed now.

**Comment by JeremyRand** [comment] 2018-06-20 08:59
Thanks @YihaoPeng, much appreciated.  It looks like BTC.TOP and Slush (both of which haven't mined a block since this issue started) have just each mined 2 blocks, which suggests that things are back to normal now that the problematic transaction is confirmed.  We'll keep an eye on the blocks being mined for a little while, but hopefully things will go smoothly from here on out.

**Comment by domob1812** [comment] 2018-06-20 09:13
Indeed, very good and thanks @YihaoPeng for your help!  Hopefully things will get back to normal now.

The proposed code fix is in #228, which will prevent this issue from arising again should another such transaction be created in the future.

**Comment by domob1812** [comment] 2018-06-25 05:54
With the presumed fix in #228 merged, I hope this is now solved for good.  Does anyone have an update on the actual current network status?  @JeremyRand, @cassiniNMC?

**Comment by JeremyRand** [comment] 2018-06-27 21:55
> With the presumed fix in #228 merged, I hope this is now solved for good. Does anyone have an update on the actual current network status?

@domob1812 A day or two before you asked that question, I looked at mining distribution stats and everything looked fine at first glance.  I don't have enough RAM to open up the mining stats VM to paste the output at this time, but I'm pretty sure that everything is resolved.

**Comment by JeremyRand** [comment] 2018-06-27 23:35
~~~
Stats from 404855 to 404954 (100 blocks):

  Total     %  Pool or Miner, Blockversion
     32  32.0  BTC.com-10104
     21  21.0  ViaBTC-10104
     14  14.0  F2Pool-10104
     10  10.0  BTC.TOP-10104
      8   8.0  slush-10104
      7   7.0  Antpool-10104
      5   5.0  unknown-10104
      3   3.0  Unknown (Coinbase /E2M & BTC-TOP/)-10104
~~~

~~~
Stats from 403955 to 404954 (1000 blocks):

  Total     %  Pool or Miner, Blockversion
    310  31.0  BTC.com-10104
    160  16.0  ViaBTC-10104
    128  12.8  BTC.TOP-10104
    127  12.7  slush-10104
    122  12.2  F2Pool-10104
     60   6.0  Antpool-10104
     53   5.3  unknown-10104
     31   3.1  Unknown (Coinbase /E2M & BTC-TOP/)-10104
      9   0.9  huobi-10104
~~~

Everything looks fine here.

**Comment by JeremyRand** [comment] 2018-06-27 23:37
@domob1812  That said, should we backport #228 to a stable branch, so that miners don't have to use master branch in order to protect themselves from the issue in the future?

**Comment by cassiniNMC** [comment] 2018-06-27 23:46
Seems indeed we can close this issue now. Everything looks back to normal including hashrate, see https://bitinfocharts.com/comparison/hashrate-difficulty-btc-nmc.html#3m

**Comment by domob1812** [comment] 2018-06-28 09:15
@JeremyRand:  I don't think it is super important to backport, as it is enough if some percentage of the hash rate has a fix to prevent an issue as big as the one we had.  Also, using `master` is probably fine.

That said, I think it should be trivial to backport, so will do that - can't hurt, either.

**Comment by domob1812** [comment] 2018-06-28 09:15
I'll reopen the issue until I've done the backport, just so I won't forget.

**Comment by domob1812** [comment] 2018-06-28 14:13
Backported 8107e23f0ed7b34222eaf576277742e21db4ecf7 to `0.16` as 4359f75d752487e7d82bfc83382c57ef6f8106df.

**Closed by domob1812** 2018-06-28 14:13 UTC
Labels: bug
