### ISSUE TITLE
No connections 

### ISSUE THREAD

**Issue by aa6** [namecoin/namecoin-core#145] opened 2017-03-10 06:18 UTC
I've compiled the master branch with static BDB4.8 and `--without-gui` flag on Raspberry Pi yesterday. It worked (behind NAT) over night but still has got zero connections. I've also added `maxconnections=20` to namecoin.conf to reduce memory usage. Is there anything I can do to synchronize with the net?

**Comment by aa6** [comment] 2017-03-12 13:19
Namecoin-legacy has found connections instantly so I believe that's not a host-related problem.

**Comment by JeremyRand** [comment] 2017-03-18 08:31
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

I suspect that it's an issue with the DNS seeds.  This may fix itself
after a day or two, or you can try to find peers from the DNS seeds
yourself with the `dig` tool and make Namecoin Core use them with the
`-addnode` flag.

Namecoin Legacy doesn't use DNS seeds, so it wouldn't be affected.

-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJYzPBLAAoJELPy0WV4bWVw2MIP/j4VGqKXNTPwXvGdmnHca/to
jqqvlLDKdqoHcQA3RTIUf1cIYpgBd7Tu407hiMeA+4SgpGbq/FjelExv4/EEpOY+
KOhVOYsvKdRFPbqPWb+Fq75qOavW9wqqunJ01Jd4lxuomlY/BYbf3o2pGU1dpsc1
p6MwhM6b2XHHkO66yN009Vkt8lRTMQilL+txwpsqJ2E1XzFbFOOs/3u+FKFnKjAT
2lKDm1koBOQM7hi3WTMG/hjK+iHJwbTLB79C2wyHa7wH1dDyhbCSXsgj5/L6LvEW
D6lq9NvudZ/Ruabtw9MB8J94wDDMTdeJXrUObjge80eYH/W9OfpeSotRAztNyk4/
swpbA8byYTglZ+pS3f/3Wv0fDDRAuffo8W39FhiieBndV++Z2R3b8y2p1+G2hT5X
ov9Ye+DrA33TvZf82WVt5IH8x6g2TiNthzHOBCEOnZOiIO1XjiBQ0y1GQXMD9nXY
GPHxHJgMDsOtrKKVQ42JhL0G5s1/Dl18gnqpIWaC/qEjo9yWrROPW0lI+gmKutv1
xm5NICPmS47dyVXgjajLzYijnImoaFQWSnamy4qiFkauUNqFdQFJboHDuq1t5ScA
IrsDppBIR3lkxY4vXIXF5VYxqjWsyJdtgmu97gCaO+AEVTaRoydgc8Ut6aFvKXbU
/J1ntulxGlUD0xhRnsYU
=oubS
-----END PGP SIGNATURE-----

**Comment by mruddy** [comment] 2017-11-22 12:51
These other issues seem to be the same thing:
https://github.com/namecoin/namecoin-core/issues/174
https://github.com/namecoin/namecoin-core/issues/188

I can reproduce this bug with latest master commit c673127ba28c618db4e63a9de1ef63d6ad704bab.

The DNS seeds return valid addresses (more info https://github.com/namecoin/namecoin-core/pull/177#issuecomment-346339327), but the node does not connect to any of them.

**Comment by mkg20001** [comment] 2017-11-22 13:32
A tmp fix for me was to run a namecoin legacy node on a vps and then launch namecoin with `./src/qt/namecoin-qt -addnode=136.243.31.32`

**Comment by mruddy** [comment] 2017-11-22 13:45
yep, `-addnode` works, even for the latest code. the latest code just doesn't seem to connect using the seed or p2p distributed addresses.

**Comment by mruddy** [comment] 2017-11-22 15:45
The root cause seems to be with the `NODE_WITNESS` service flag. I changed some code dealing with that service flag, like `GetDesirableServiceFlags` and some code in `AppInitMain` and now I'm able to connect to some other nodes like normal. I may dig into this and come up with a pull request. If not, at least someone else can look in this area.

**Comment by domob1812** [comment] 2018-06-07 16:09
Presumably fixed now with #198.

**Closed by domob1812** 2018-06-07 16:09 UTC
