### ISSUE TITLE
Boost dependencies nolonger availabe on ubuntu / apt-get

### ISSUE THREAD

**Issue by keynan** [namecoin/namecoin-core#48] opened 2015-11-25 08:00 UTC
apt-get now serves boost 1.58 preventing namecoin installation.
1.58 can not be uninstalled without removing a host of dependent software

**Comment by domob1812** [comment] 2015-11-25 08:11
Namecoin Core follows Bitcoin Core with respect to things like this, so you should most probably file this to upstream Bitcoin.

**Comment by JeremyRand** [comment] 2015-11-25 08:41
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

On 11/25/2015 02:11 AM, Daniel Kraft wrote:
> Namecoin Core follows Bitcoin Core with respect to things like
> this, so you should most probably file this to upstream Bitcoin.

Agreed.  However, IMO you should be doing a Depends build or a Gitian
build, not relying on the Ubuntu package repos.  So this is not really
a big issue as far as I can tell.
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQIcBAEBCAAGBQJWVXQ/AAoJEAHN/EbZ1y06D1kQAIIgAg44GK2cdOPorU85PXVH
lKQb2Cm+mELF/jEDL0a8b74EZd9QsQGgqTB5fJw7kMX7D7y6+0buMCDotFU4kHno
D7Wrd7C1r/TLZtZHYwqZJOfqfgjnubrZu8DotnYntV+2lbiiuRyuly/nHoFA0Zmq
eQQxXHuUtyFXxKyYYoiiUQsR+FJSdAU0KzbjSMZd4bhMUawlOvcbZj/ANCmGmvG6
kQxlHQ/KyXxuEHBnk1W4ESSlS5CV/7jpH7gT+enwiLrLzCmp9iptK2DpJcg974bO
ywNFG3rtCAxm+8LXQrR+ttUAD6BwGCH70PNwVY+tmqXDSyqVhXNJn1to2+5Z1L/o
Ob0aq0KglbCHA9qdTmS+ET1R6gTDbeZhaQcYOh4S8mkA9rXp8Da8scvul6XUXsZL
OljTAac7p6+1f0K0IG06o0fE+moXzP9lZlqRJybWHcPk5nZHCJFga2MYpqwgt7hl
Kf3YJ54HPruRG1moA93QTylO/BtgQwcyveMbcqeuLJonB994SaaVQj4NqjJaaqkN
rgS7sFmjrSQ5inDZRUwviYNFAm52kY/ht+zoZVauF5cajAphNaOFRGmX9Hn4xrgr
1zyKyJY3w2BM6rnJidCtTEMtg8ZwD+dv38axVWTnwZcroqMIHI9cU6daa2aSTeWV
1jwwGs1icZw3DgC9WQdJ
=ZMzI
-----END PGP SIGNATURE-----

**Comment by fsb4000** [comment] 2016-01-15 17:50
What's wrong with boost 1.58? I built namecoin core with boost 1.58 on Windows without problems....

**Comment by phelixbtc** [comment] 2016-01-16 11:07
>What's wrong with boost 1.58? I built namecoin core with boost 1.58 on Windows without problems....
This.

**Comment by JeremyRand** [comment] 2016-01-20 02:18
@fsb4000 @phelixbtc I wouldn't be surprised if Boost is consensus-critical code.  Meaning that changing the version without careful testing/analysis could cause consensus failure.  Remember that this has already happened twice with OpenSSL.

**Comment by phelixbtc** [comment] 2016-01-20 10:03
@JeremyRand The current Windows release was built with 1.58. It has been the default in EasyWinBuilder since at least 2015-07-07. What is the current boost version in Gitian for v0.11.x and v0.12 ?

**Comment by JeremyRand** [comment] 2016-01-20 10:12
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

@phelixbtc See this:

https://github.com/bitcoin/bitcoin/blob/master/depends/packages/boost.mk

In Bitcoin Core 0.11, they used Boost 1.55.0.  Bitcoin Core 0.12
updated to Boost 1.59.0.  So far they haven't changed this in the
master branch since 0.12 branched off, so 1.59.0 is what master branch
uses at the moment.

I don't know for sure how much Boost is used in consensus-critical
code, but it's probably safest to do what Bitcoin Core does, i.e. we
probably shouldn't change the Boost version that we use except when
Bitcoin Core does so.  Particularly because the last time there was a
consensus failure risk (in OpenSSL), the Bitcoin devs didn't tip us
off in advance.
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQIcBAEBCAAGBQJWn1YuAAoJEAHN/EbZ1y06YuEP/10hjebIKk1x8naXAWIQQNP7
vT59/QxhA45tN8C9CUznafV2NZ3Denn3hdzyyszzYKhe2fg+6ttbNTpDy4LlQff6
4cMuJkno8enf3l59BGHG2sj5fS+LEuM+V0+bwk1E+p3mPIEfl2tKZyj6aH8TKMhz
m5lhn/3inFT2Y/sm5Fi7E5vOt1FMnph6mnUd1IdYPoU1s8lvAyB3/YZOgAvEFD09
eSPYsjbtekSx8QZcI05Bvw8QZ8jk+bTHtG1ABLoYEeKOwGHaXkMmNukE92YP6Si3
mB0hw2M/pEK5hzRAGTZfH+ZfSl1SZ9MwQ+A58hvetvkW+ELcZmV5caaJ5vmE/2po
bR1fiQ+qKLiooY0besC8NBVTUwHqgEU/jK0xB4wOLIQiiceGcz76dMcnOacXK9+C
LX3zAv6qzQrPr0HQ7+g3Hrgunb9pjtdDcEiTsCS3SatoV6oqKhnD6pxcaoBf6EhJ
vLzCXCw6WCaBmWR61MZn33/Fz4CiWjPw8heW+9O9waoMjo8cH/D045LxHaEU2x+2
TAbTTABEOVD9Nbo52K//8tNJ+CPqb6YTnc3C6LDuxf6MyMY4B/6peEdM4ot36cBM
DjmYsv3PjF3OQg0O1jtIv8fawDKJxgLAjYLxCNN/kL888h34pVUJROUxNcmu2fA+
loM1KDMdB9/GC2ywBfHo
=FLBu
-----END PGP SIGNATURE-----

**Comment by JeremyRand** [comment] 2016-02-21 00:09
Since Bitcoin Core has updated past 1.58 as of 0.12, can we close this?  @keynan are there still any issues?

**Comment by JeremyRand** [comment] 2016-02-26 01:20
AFAICT the issue is fixed since Bitcoin Core has updated Boost as of 0.12.  If anyone wants to keep this issue open, please say so in the next 72 hours.

**Comment by JeremyRand** [comment] 2016-03-06 03:00
Closing since this appears to be fixed.  Feel free to reopen if any issues persist.

**Closed by JeremyRand** 2016-03-06 03:00 UTC
