### ISSUE TITLE
Sync is inexplicably slow

### ISSUE THREAD

**Issue by Atraps003** [namecoin/namecoin-core#218] opened 2018-05-12 08:50 UTC
I have a full namecoind node that has 1 gb connection speed. This node is fully synced. When I connect a new node that needs a full sync to my 100% synced full node, it will idle most of the time not syncing. This is not a resource issue.

Both nodes have plenty of free CPU, memory, drive IOPS, and internet bandwidth but these resources are not utilized to sync quickly. It took ~24 hours to sync the ~5 GB namecoin blockchain. Bitcoin takes half the time to sync ~150 GB. Both nodes are version 13.99.

**Comment by domob1812** [comment] 2018-06-05 11:34
That is strange.  Last time I tried a full sync, it worked fine for me (but it is some time ago).

Does your `debug.log` show anything interesting?  (E. g., lots and lots of some message repeated all the time.)

**Comment by domob1812** [comment] 2018-06-08 08:14
My sync is now finished.  It took in total 1 hour and 20 minutes, with both nodes running on my 6-year-old laptop without SSD and while doing some development work in the background.  During all the time (after the initial header sync) the `namecoind` was CPU-bound and using at least one full core.

So it seems I cannot reproduce the issue you see.  @Atraps003, can you perhaps try again with a build from latest sources?  My test was done using a build from `master` just a few weeks old (version 0.16.99).

**Comment by JeremyRand** [comment] 2018-06-13 09:57
I've regularly observed a ~24-hour sync time on 0.13.99-name-tab-beta1, but can't reproduce it on recent master branch (it took about half an hour on my Talos II; 1 hr 20 min sounds not too far off what I would expect for a 6-year-old x86 laptop).  I suspect that this was fixed by https://github.com/namecoin/namecoin-core/pull/198 .

**Comment by domob1812** [comment] 2018-06-13 10:07
Thanks for checking - #198 sounds like a plausible reason for the fix.  Then I'll close the issue for now - anyone feel free to reopen if it can be reproduced with a fresh build.

**Closed by domob1812** 2018-06-13 10:07 UTC
Labels: needs information
