### ISSUE TITLE
RPC call for matching names by prefix.

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/namecoin-core#16] opened 2015-07-06 05:42 UTC
name_filter's RegExp parsing is way overkill for the standard use case of prefix matching.  I suggest adding a new RPC call that returns all names that match a specific prefix.  The format should be similar to the output of name_filter.

**Comment by domob1812** [comment] 2015-07-06 05:47
In the future, `name_scan` will be changed to sort lexicographically instead of "short names first".  This will automatically allow a very efficient version of prefix filtering without a new RPC command.  It is already so in my `uno-trie` branch.  Should I merge just this order change already to master?

**Comment by JeremyRand** [comment] 2015-07-06 05:52
@domob1812 If I recall correctly (and it's been a while since I used name_scan), name_scan has a limit on the number of names returned, while name_filter does not.  This makes name_filter more useful for some applications.  Is there a way to make name_scan allow returning all names for a prefix with a single RPC call?

**Comment by domob1812** [comment] 2015-07-06 05:58
No, but you can just call with a fixed number of names and use the last returned name as new start.  This is how it was intended, I guess, and it should be efficient.  Returning a possible large number of names leads to problems with potential time outs or too much memory usage.  I think that you should definitely use multiple calls especially if you try to do things like get all `d/` names.

**Comment by domob1812** [comment] 2018-06-07 13:28
@JeremyRand:  What do you think about this old issue?  I think that `name_scan` and `name_filter` already provide enough complexity, and we should not add yet another "scanning" RPC.  Especially `name_filter` is already quite complicated, in addition.

A longer shot to clean all of this up would be to target a single RPC with an `options` argument, similar to your proposal in #194.  I. e., we could add such an argument to `name_scan`, so that one can optionally filter by regexp, by prefix, confirmation number and all that.  WDYT?

**Comment by domob1812** [comment] 2018-07-02 06:10
As written in my last comment, I suggest to resolve this via #237.  I'll close this issue - but if someone disagrees with my proposal, feel free to reopen.

**Closed by domob1812** 2018-07-02 06:10 UTC
Labels: enhancement, rpc
