### ISSUE TITLE
Restore RPC "toaddress"

### ISSUE THREAD

**Issue by redarmyfaction** [namecoin/namecoin-core#530] opened 2023-01-06 16:20 UTC
The current RPC command, which introduced so-called options by Daniel Kraft @domob1812 in https://github.com/namecoin/namecoin-core/pull/220, is completely broken. 

Names that are not in the hardcoded d/ dd/ id/ idd/ namespaces cannot be transferred.
`&namespace/name`, for example, will **fail miserably**. Nearly losing names in https://github.com/namecoin/namecoin-core/issues/524

Worse, after such a "option" transfer, `name_show` returns a different owner for the name in RPC and console. 
**RPC displays a different owner than the console.** 

**Propose to restore Namecoin inventor Vincent Durham (@vinced) [original RPC command](https://github.com/vinced/namecoin#running)**:

**namecoin-cli name_update "myname", "new-value", "NE00nME0p0iyNK0gFh0FUeUriHXxEFemo0"**

`namecoin-cli name_update name value toaddress`

**Comment by JeremyRand** [comment] 2023-01-06 23:16
Duplicate of https://github.com/namecoin/namecoin-core/issues/524

**Closed by JeremyRand** 2023-01-06 23:16 UTC
Labels: duplicate
