### ISSUE TITLE
Managed names still showing transferred names

### ISSUE THREAD

**Issue by jrkenn** [namecoin/namecoin-core#268] opened 2018-10-20 14:34 UTC
I have transferred several .bit domain names to another wallet I have and the domain names are still showing in both wallet accounts on the manage names tab. Both wallets are Namecoin Core version nc0.13.99-name-tab-beta1 (64-bit) with the QT version 5.6.1. All the transactions show in both transaction windows for both wallets cores and are both receiving confirmations. I have tried restarting the core but that doesn't work to fix the duplicate names. They are still there

**Comment by inspiraluna** [comment] 2018-11-05 11:52
On nc0.16.2 /nc0.16.3 transfered names are still visible when calling namecoin-cli name_list even though it shows an address which doesn't belong to that wallet. I do not know if this is a desirable function.

**Comment by domob1812** [comment] 2018-11-05 14:20
@inspiraluna: `name_list` is expected to show all names that "ever touched" your wallet.  The ones that are no longer in it are marked with `ismine: false`.  (`transferred: true` in previous versions.)  So unless you see those names marked as `ismine: true`, it is expected behaviour.

**Comment by jrkenn** [comment] 2018-12-20 19:45
I do hope this is something that can be changed. Take a look at how the emercoin is set up. Once a name is transferred to another person it falls off your main list but there are sections to see what domains you own and the ones you have transferred that are now owned by another party.

**Comment by domob1812** [comment] 2018-12-20 20:30
It can sure be changed - but I think the RPC interface (i.e. `name_list`) is not the right place for this.  What you are mainly asking for is a change in the Qt UI.  `name_list` is meant to be used either by front-ends, developers or perhaps power users - all of them should be aware of how it works.  Filtering out names based on `ismine` is not hard, and something that said front-ends should do (plus the Qt UI).

**Comment by jrkenn** [comment] 2018-12-20 21:07
It is the QT I use and maybe in a later release they can look at this and change it it in the QT UI. Other than this works good.

**Comment by JeremyRand** [comment] 2021-08-23 19:57
Duplicate of https://github.com/namecoin/namecoin-core/issues/212

**Closed by JeremyRand** 2021-08-23 19:57 UTC
Labels: bug, qt
