### ISSUE TITLE
Core config and start arguments - bind, rpcbind won't work

### ISSUE THREAD

**Issue by e-x** [namecoin/namecoin-core#168] opened 2017-05-22 07:59 UTC
When start as:
$ namecoind -rpcbind=10.1.1.7 -bind=122.2.6.1 -rpcallowip=10.1.1.7
or in config file:
rpcbind=10.1.1.7
rpcallowip=10.1.1.7
rpcallowip=127.0.0.1
bind=122.2.6.1
externalip=122.2.6.1
namecoind  always started on all network interfaces 
$ netstat -an | grep namecoind  
user        namecoind  13270 5  tcp4   *:10337               *:*
user        namecoind  13270 9  tcp4   *:10336               *:*

**Comment by JeremyRand** [comment] 2017-05-22 08:20
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

e-x:
> When start as:
>>> namecoind -rpcbind=10.1.1.7 -bind=122.2.6.1
>>> -rpcallowip=10.1.1.7
> or in config file: rpcbind=10.1.1.7 rpcallowip=10.1.1.7 
> rpcallowip=127.0.0.1 bind=122.2.6.1 externalip=122.2.6.1 namecoind
> always started on all network interfaces
>>> netstat -an | grep namecoind
> user        namecoind  13270 5  tcp4   *:10337               *:* 
> user        namecoind  13270 9  tcp4   *:10336               *:*

What version of Namecoin Core?  Have you checked a comparable version
of Bitcoin Core to see if the issue is reproducible there?


-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJZIp8HAAoJELPy0WV4bWVwAZ8P/RAen2q21z7RjWz8Asey4wGG
IwKWnbZpHvw1s5wmofgh6mVxxU8Sw2b9dLV0qhugNZvSIzidn3QvJmUdtb5UHjxY
kK7Ji05qOEwrwzGp/EAsQtm1R2LiIzG6KV/5al0Wo5ZFpIGY7IA3MRsbLuoK9GOu
sfMgWFGtVgypVG8MHxIiYLEYNmi0MrYkOxPRNLeLiXYY1Fd19C/Z5fp/Q6bmC0Uh
9sIGIzZb8nEsfEqQ/5RB9SSlGz+zBS6usofO1ZK/FtaYO4YkeY7edx4mlxn7lChR
UODu8AZU4QEehaISKyfgHNDCp2h7y3iLtdUlAPO+ib2ITeEwl9u+w8Jpo3evH0rq
pmHUmCbWK12P0MMOoEGOP3xNNpH1WyGbwGh8CXB/gDCB5/RDBju9M0k6gr/mRzf9
QuEXZIBmXaoCveGRuUJ0F+RqRhYBPOAac08rCDl8VRzFs33wxynfCE+lbA7pfnGm
Cs8hj11nP7j+P7iwoZAMzzwTKkGyI1jNjfRC+8CGuC6TBwPYZ5yF5T6XrflHRxjM
wI9oxn2aMQVEFLiAAvgLhgdI/B61zrmMXVDARDzQE0YAF5AZEufAToLuhSMzqU22
2r8XbtD9YHz4lDJss1LLkPkLobpTs9bGerchNEVKWFMZSQsabzjrfjn2/zZOJtRg
YmJ43oOrLAbPm7oltxhn
=Hiuo
-----END PGP SIGNATURE-----

**Comment by e-x** [comment] 2017-05-22 09:25
sry
namecoin version 0.3.80
which version of bitcoin is "comparable" for check ?
Bitcoin Core Daemon version v0.12.1.0 working fine

**Comment by JeremyRand** [comment] 2017-06-05 09:21
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

e-x:
> sry namecoin version 0.3.80 which version of bitcoin is
> "comparable" for check ? Bitcoin Core Daemon version v0.12.1.0
> working fine
> 

Current binary release of Namecoin Core is 0.13.99-name-tab-beta1,
which is based on Bitcoin Core 0.13.99.  If possible, it would be best
to test against Namecoin Core master branch.

-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJZNSJ/AAoJELPy0WV4bWVwmkQP/jxV6O2AsBykMZkoB0FHfHTn
24EvDOJ0Qa26Pm2EBLx5Ob0gX3H8sPI49e5T8AWgf+oPz6tAPso6/QztetRVmgos
b5gH96Fn/rtf45nV0zBQbhaDnEUwawJXLTqeQoTiUTXrmabkzGcrld3LLe5oPZLf
qIh/edIjXfKiOkuhqf/ct+LPyAHE4u86mI+LRjNgkEP0T3KM0aWicgZ27t3BQ+AR
B7crW/5BbfDvKraiynEGu127Hv7P5GsfwOyL9wfXXnNfK3hv7ueVTQ5pTz9BWM+L
GmSDQyyATodV/Gn8h22yhSYrDJ1BwYK79N74oJ0tqnO85b8I/mHfMzWHgACOAgj+
KhSc32SW3GGYEBP+SaQrfyobUcfnIBOzQ6zv754EUlfaLwiUo6gBA0Fku/Ssszut
O8N/DmB0YaMnu3hfTikKCco8Gcpnvv43cneDVqQENGrwQ9yC9V/G7YMKoHcfP/oc
SeQLVnU4Oja2uh33jmjZQRmAY+S0fJ2pgtphW8Os6wF+ASNcKqTesTXIM62vA/mb
C2uRPYg4VopcpVKW1KapW1XgCuS3UibkXZZ6EDNnBm09KXCKpSCe1f4eRfVZnOIX
iTDs8v3+bwPC6wf3BcPpP3g/KUXJQg9OWsJBL47ikUws2OuII+A5zYQp4TjcRCWN
8VkBtahWruhB2ouhJ6Zu
=59qu
-----END PGP SIGNATURE-----

**Comment by JeremyRand** [comment] 2017-08-06 14:12
Closing since 0.3.80 isn't covered by this repo, feel free to open a new issue if you encounter this in Namecoin Core.

**Closed by JeremyRand** 2017-08-06 14:12 UTC
