### ISSUE TITLE
name_update should affect name_show before it is mined

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/namecoin-core#24] opened 2015-08-07 08:34 UTC
Right now, a name_update needs 1 confirmation before it affects name_show.  I think this is suboptimal.  If a name owner believes that a key (e.g. a TLS key) referenced in the name is compromised, right now it will take on average 10 minutes for the key to be revoked.  That could be a significant amount of compromised traffic for a high-traffic website.  Similarly, if a name owner has messed up the configuration of a name, he will have to wait on average 10 minutes for his website to work again, which is a significant amount of downtime for a high-traffic website.  Accepting unconfirmed name_update transactions would improve security and reduce downtime in such cases.

Usually, waiting for confirmations is used as a protection against double-spending.  But in this case, that attack doesn't make any sense.  A name owner has no motivation to double-spend his own name unless he's selling it non-atomically (a roughly useless use case), and in that case the value of the name is still not considered compromised (unless the recipient is stupid enough to point their end users at the transferred name before the transfer has been confirmed, which is also a roughly useless use case since it will have a value chosen by the original owner).

It could, maybe, be argued that forcing name_update operations to wait for a confirmation would increase the incentive to offer a high fee -- but I think requiring the name_update to meet relay requirements may be sufficient.  If not, we could also watch previous blocks and enforce the fee based on those, using the same code that Bitcoin Core uses to guess good fees for our own transactions, e.g. require that an unmined name_update meet our predicted fee for being mined within 6 blocks.  (1 block wouldn't work, because if that increases between blocks, then transactions created right before that block transition wouldn't be accepted.)

**Comment by domob1812** [comment] 2015-08-07 08:55
I understand your arguments why double-spending is not an issue here, and it would also be fairly easy to code (especially since the mempool already keeps track of names being updated, so it can prevent updating the same name twice).  I could write up a patch that does this relatively easily.

However, I think this is at least a potentially controversial change - thus I would like to get more opinion from others.  The main feature of Bitcoin and Namecoin simply is the blockchain consensus, and thus I can also see why it makes sense to only update the name database after the first confirmation.  Doing as you suggest has the potential to make the result of `name_show` much more uneven across the network as today.  I agree with you that I do not see a big issue with that, but who knows; it could very well introduce new attack vectors we are not yet thinking about.

Is it really so critical to revoke a TLS key within 10 minutes?  I assume it takes you much more time in the beginning to figure out the key has been compromised.  No?

What about adding `name_pending` again to Namecoin Core - this would enable a "high level" application like NMControl to get the data and decide for itself whether or not to use the unconfirmed transaction for a particular thing.  It could do so for fingerprints, for instance, and not do so for some other, less urgent namespaces.

**Comment by phelixbtc** [comment] 2015-08-07 09:07
The address should not change up front. `name_pending` sounds like a good solution. It would also be helpful for nameGUI (where I currently use `listtransactions` to read out pending name operations).

**Comment by JeremyRand** [comment] 2015-08-08 06:55
What would be the behavior of name_pending?  Same as name_show if no update is pending, but if an update is pending it would use that transaction instead?  I guess I'd be okay with that, but I can't really think of any use cases where a user would prefer outdated values; wouldn't they be using name_history if they wanted that?

**Comment by domob1812** [comment] 2015-08-08 14:18
Well, same as `name_pending` in the old client.  I. e., it returns you a list of all name operations in the mempool.  This can be used by NMControl to trivially modify `name_show` results if it wants to handle unconfirmed transactions.

I think that `name_show` should return the most recent value of the name/value database.  As I've stated already above, I think this should really only take confirmed tx into account.  That's what sets Namecoin apart from a non-blockchain consensus system, and is thus somewhat the "main innovation".  We shouldn't get rid of that just because we can not imagine why someone would want this.  With `name_pending` added, the high-level applications can decide for themselves what they want to do with all data that is available and how to combine confirmed with unconfirmed name operations.

**Comment by JeremyRand** [comment] 2015-08-08 21:32
What about the edge case that there is a chain of two (or more) updates for a name in the mempool?  Will name_pending make it easy to determine the ordering of the chain?

**Comment by domob1812** [comment] 2015-08-09 08:11
That's not possible, since the mempool only allows a single pending tx for each name.

**Comment by phelixbtc** [comment] 2015-08-26 07:41
About to close - https://github.com/domob1812/namecore/issues/11

**Comment by JeremyRand** [comment] 2015-08-26 16:19
@phelixbtc Until it's merged, I'd prefer to keep this issue open.

**Comment by JeremyRand** [comment] 2015-08-26 17:37
@domob1812 is the "single pending name tx per name" rule part of blockchain validation, or just the behavior of the current client?  Does a similar rule exist for currency outputs?  I'm not entirely sure what the purpose of that rule is.

**Comment by domob1812** [comment] 2015-08-26 20:02
I think it is only a rule of the current client and not strictly enforced by block validation rules.  I know you would like to see the possibility to issue quick updates after each other, but I don't think that re-updating a pending name is the way to go.  If the blockchain validation process is too slow for some usecase you have in mind, we should use some kind of DHT with validation via blockchain-stored keys.

**Comment by domob1812** [comment] 2015-08-29 16:16
https://github.com/namecoin/namecore/commit/91a2a2e5ae0e0ed3853adbf2a36e78018e6c7aaa is now pushed to master.

**Comment by phelixbtc** [comment] 2015-08-29 18:59
Quick updates might be possible via (first seen safe) RBF. Could this be used for some hacky UDP like broad cast? @JeremyRand is there a particular use case you have in mind?

**Comment by JeremyRand** [comment] 2015-09-29 19:39
@domob1812 DHT's have their own issues.  I don't think it makes sense to enforce a policy that quick updates must use a DHT.

@phelixbtc RBF = replace-by-fee?  Yes, I think that could possibly accomplish this.  Does RBF enable any kinds of attacks on name updates?  It would make it easier to reverse name sales, but with atomic name trades I don't see how that's a significant threat.

**Comment by domob1812** [comment] 2018-06-07 13:35
Closing this per the discussion about `name_pending` (which is implemented now).  Also #194 might enable an option to see unconfirmed values for `name_show`.  Feel free to reopen if you think this issue is not adequately covered by these, though.

**Closed by domob1812** 2018-06-07 13:35 UTC
